input {
  tcp {
    port => "${LOGSTASH_TCP_PORT:5000}"
    codec => json_lines
  }
}

filter {
  json {
    source => "message"
    skip_on_invalid_json => true
    remove_field => ["message"]
  }

  if [level] == "ERROR" {
    mutate { add_field => { "[@metadata][index]" => "error-logs" } }
  } else if [level] == "WARN" {
    mutate { add_field => { "[@metadata][index]" => "warn-logs" } }
  } else if [logType] == "API" {
    mutate { add_field => { "[@metadata][index]" => "api-logs" } }
  } else {
    mutate { add_field => { "[@metadata][index]" => "app-logs" } }
  }
}

output {
  elasticsearch {
    hosts => ["http://${ELASTICSEARCH_HOST:timo-elasticsearch}:${ELASTICSEARCH_PORT:9200}"]
    index => "%{[@metadata][index]}-%{+YYYY.MM.dd}"
  }
}